#scadalts-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scadalts.fullname" . }}
  namespace: v-ics
  labels:
    app.kubernetes.io/name: {{ include "scadalts.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "scadalts.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "scadalts.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scadalts
    spec:
      containers:
        - args:
            - /usr/bin/wait-for-it
            - --host=database
            - --port=3306
            - --timeout=30
            - --strict
            - --
            - /usr/local/tomcat/bin/catalina.sh
            - run
          env:
            - name: CATALINA_OPTS
              value: "-Xmx512m -Xms512m"
            - name: MYSQL_USER
              value: scadalts
            - name: MYSQL_HOST
              value: {{ include "scadalts.fullname" . }}-mysql
            - name: MYSQL_USER
              value: {{ .Values.database.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.database.password }}
            - name: MYSQL_DATABASE
              value: {{ .Values.database.database }}
          image: scadalts/scadalts:latest
          name: scadalts
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
