#scadalts-service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scadalts.fullname" . }}
  namespace: v-ics
  labels:
    app.kubernetes.io/name: {{ include "scadalts.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.scadalts.service.type }}
  ports:
    - port: {{ .Values.scadalts.service.port }}
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "scadalts.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
