#database-claim0-persistentvolumeclaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
  namespace: v-ics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  hostPath:
    path: "./db_data"

---
#database-claim1-persistentvolumeclaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-conf-pvc
  namespace: v-ics
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  hostPath:
    path: "./db_conf"
