apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: scadalts
  name: scadalts
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: scadalts
