# scadalts-claim0-persistentvolumeclaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: scadalts-claim0
  name: scadalts-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
