apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: v-ics
type: Opaque
data:
  root-password: cm9vdA==  # base64 encoded value of 'root'
  user-password: cm9vdA==  # base64 encoded value of 'root'
