apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  database-url: database-service

---

#database-claim0-persistentvolumeclaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
  namespace: v-ics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  hostPath:
    path: "./db_data"

---
#database-claim1-persistentvolumeclaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-conf-pvc
  namespace: v-ics
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  hostPath:
    path: "./db_conf"

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: v-ics
type: Opaque
data:
  root-password: cm9vdA==  # base64 encoded value of 'root'
  user-password: cm9vdA==  # base64 encoded value of 'root'

---

#database-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  name: database-deployment
  namespace: v-ics
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: mysql
          image: mysql/mysql-server:8.0.32
          args:
            - --log_bin_trust_function_creators=1
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
            - mountPath: /etc/mysql
              name: mysql-config
              readOnly: true
          env:
            - name: MYSQL_USER
              value: scadalts
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: database-service
      restartPolicy: Always
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-pvc
        - name: mysql-config
          persistentVolumeClaim:
            claimName: mysql-config-pvc
---
#database-service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database-service
spec:
  ports:
    - name: "mysql"
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: database

---

# scadalts-claim0-persistentvolumeclaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: scadalts-claim0
  name: scadalts-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

#scadalts-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  name: scadalts-deployment
  labels:
    app: scadalts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scadalts
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scadalts
    spec:
      containers:
        - args:
            - /usr/bin/wait-for-it
            - --host=database
            - --port=3306
            - --timeout=30
            - --strict
            - --
            - /usr/local/tomcat/bin/catalina.sh
            - run
          env:
            - name: CATALINA_OPTS
              value: "-Xmx512m -Xms512m"
            - name: MYSQL_USER
              value: scadalts
            - name: MYSQL_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: mysql-secret
                  key: user-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: mysql-secret
                  key: root-password
            - name: DB_HOST
              value: database-service
          image: scadalts/scadalts:latest
          name: scadalts
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/local/tomcat/logs
              name: scadalts-claim0
      restartPolicy: Always
      volumes:
        - name: scadalts-claim0
          persistentVolumeClaim:
            claimName: scadalts-claim0
---
#scadalts-service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: scadalts
  name: scadalts-service
spec:
  type: NodePort
  ports:
    - name: "web"
      port: 8080
      targetPort: 8080
    - name: "debug"
      port: 8000
      targetPort: 8000
      nodePort: 30000
  selector:
    app: scadalts
