apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.instanceName }}
  labels:
    app: openplc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: openplc
